/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Book */

#ifndef _Included_Book
#define _Included_Book
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Book
 * Method:    getSymbolBook
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Book_getSymbolBook
  (JNIEnv *, jobject);

/*
 * Class:     Book
 * Method:    getBidValueBook
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_Book_getBidValueBook
  (JNIEnv *, jobject);

/*
 * Class:     Book
 * Method:    getBidSizeBook
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_Book_getBidSizeBook
  (JNIEnv *, jobject);

/*
 * Class:     Book
 * Method:    getOfferValueBook
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_Book_getOfferValueBook
  (JNIEnv *, jobject);

/*
 * Class:     Book
 * Method:    getOfferSizeBook
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_Book_getOfferSizeBook
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
